# Generated by Django 2.1.3 on 2020-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0002_auto_20200607_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='image'),
        ),
    ]
