# Generated by Django 2.1.3 on 2020-06-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0003_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
