# Generated by Django 2.1.3 on 2020-06-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0006_auto_20200607_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default='', max_length=5),
        ),
    ]
